# Generated by Django 5.2.12 on 2026-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="task_files/"),
        ),
    ]
